%YAML:1.0

leftCam_fx: 762.725
leftCam_fy: 762.725
leftCam_cx: 640.5
leftCam_cy: 360.5

rightCam_fx: 762.725
rightCam_fy: 762.725
rightCam_cx: 640.5
rightCam_cy: 360.5

baseline: 0.4



window_width: 1280
window_height: 720

viewer_point_x: 0
viewer_point_y: 0
viewer_point_z: -1
viewer_point_f: 762.725